name: my_portfolio
description: My Portfolio Flutter Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Freezed
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  #GetIt
  get_it: ^7.6.4

  #AutoRoute
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2

  #Dartz
  dartz: ^0.10.1

  #BloC
  flutter_bloc: ^8.1.3

  #Dio
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  #Json
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  localization: ^2.1.1

  #Font awesome
  font_awesome_flutter: ^10.6.0

  #Google font
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  #Build Runner
  build_runner: ^2.4.7

  #Json
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/i18n/
